# Generated by Django 4.2.4 on 2023-08-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_city_user_pin_user_profile_pic_user_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_profile')),
                ('category', models.CharField(blank=True, choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid 19', 'Covid 19'), ('Diabetes', 'Diabetes')], max_length=40, null=True)),
                ('status', models.CharField(blank=True, choices=[('Published', 'Published'), ('Draft', 'Draft')], max_length=20, null=True)),
                ('summary', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
