# Generated by Django 4.2.4 on 2023-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20, null=True),
        ),
    ]
